openapi: 3.0.0
security: []
info:
  title: font.delivery REST API
  version: 1.4.0
  description: The REST API for font.delivery
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://font.delivery/api/v1
paths:
  /fonts.json:
    get:
      operationId: getFonts
      summary: Get a list of all font families
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required: ["id", "name", "designer"]
                  properties:
                    id:
                      type: string
                      description: Unique identifier for the font family
                      example: archivo-narrow
                    name:
                      type: string
                      description: Name of the font family
                      example: "Archivo Narrow"
                    designer:
                      type: string
                      description: Name(s) of the designer(s)
                      example: "Omnibus-Type"
  /fonts/{id}.json:
    get:
      operationId: getFontByID
      summary: Get details for a specific font family
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the font family
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required: ["id", "subsets", "styles"]
                properties:
                  id:
                    type: string
                    description: Unique identifier for the font family
                    example: "archivo-narrow"
                  subsets:
                    type: array
                    description: Available subsets for the font family
                    example: ["latin", "latin-ext", "vietnamese"]
                    items:
                      type: string
                      enum:
                        - latin
                        - latin-ext
                        - vietnamese
                  styles:
                    type: array
                    description: Available styles for the font family
                    example: ["normal", "italic"]
                    items:
                      type: string
                      enum:
                        - normal 
                        - italic
        '404':
          description: Font family not found
