openapi: 3.0.0
info:
  title: font.delivery REST API
  version: 1.2.0
  description: The REST API for font.delivery
servers:
  - url: https://font.delivery/api/v1
paths:
  /fonts.json:
    get:
      summary: Get a list of all fonts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Unique identifier for the font
                      example: archivo-narrow
                    name:
                      type: string
                      description: Name of the font
                      example: "Archivo Narrow"
                    designer:
                      type: string
                      description: Name(s) of the font designer(s)
                      example: "Omnibus-Type"
  /fonts/{id}.json:
    get:
      summary: Get details for a specific font
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the font to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique identifier for the font
                    example: "archivo-narrow"
                  subsets:
                    type: array
                    description: Available subsets for the font
                    example: ["latin", "latin-ext", "vietnamese"]
                    items:
                      type: string
                      enum:
                        - latin
                        - latin-ext
                        - vietnamese
        '404':
          description: Font not found
