build:
	go build ./cmd/builder

test:
	go test -coverprofile=coverage.out ./...

fmt:
	gofumpt -w .

serve:
	miniserve --compress-response dist/

generate-api-files: build
	./builder --input-dir=fonts/ --output-dir=dist/

generate-api-reference:
	mkdir -p dist/reference
	redocly lint api.yml
	redocly build-docs --output=dist/reference/index.html api.yml
