name: Build (and release) fontdl

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "just package-fontdl"
      - uses: softprops/action-gh-release@v2
        # Only release if tag is on format fontdl-{version}
        if: startsWith(github.ref, 'refs/tags/fontdl-')
        with:
          files: bin/*
