name: Build

on: push

jobs:
  build-and-test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "just build"
        working-directory: ./api
      - run: nix-shell --run "just test"
        working-directory: ./api
      - run: nix-shell --run "just generate-api-docs"
        working-directory: ./api
  build-and-test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "just build"
        working-directory: ./cli
      - run: nix-shell --run "just test"
        working-directory: ./cli
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-shell --run "just build"
        working-directory: ./web
